--- a/security/Makefile
+++ b/security/Makefile
@@ -1,4 +1,5 @@
obj-$(CONFIG_SECURITY)			+= security.o
obj-$(CONFIG_SECURITYFS)		+= securityfs/
obj-$(CONFIG_SECURITY_SELINUX)		+= selinux/
+obj-$(CONFIG_BASEBAND_GUARD)		+= baseband_guard/
obj-$(CONFIG_SECURITY_APPARMOR)		+= apparmor/

diff --git a/security/baseband_guard/Makefile b/security/baseband_guard/Makefile
new file mode 100644
index 0000000..e1f2g3h
--- /dev/null
+++ b/security/baseband_guard/Makefile
@@ -0,0 +1,2 @@
# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BASEBAND_GUARD) += baseband_guard.o

